// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCIXWrvhqLKuQ-XOpb7g37vCvxTCj30L6Q',
    appId: '1:112889610100:web:341f437fba0fa4a6d63621',
    messagingSenderId: '112889610100',
    projectId: 'sptify00010101',
    authDomain: 'sptify00010101.firebaseapp.com',
    storageBucket: 'sptify00010101.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCVD4nQBnA66gfEug_HKNfe8E8urdfv1qk',
    appId: '1:112889610100:android:5d207ca0bd682696d63621',
    messagingSenderId: '112889610100',
    projectId: 'sptify00010101',
    storageBucket: 'sptify00010101.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDoJP0kIznOV6xheWzd99ihkDSV43gGzrA',
    appId: '1:112889610100:ios:ff5507b9e9fdd300d63621',
    messagingSenderId: '112889610100',
    projectId: 'sptify00010101',
    storageBucket: 'sptify00010101.appspot.com',
    iosBundleId: 'com.example.spotifyApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDoJP0kIznOV6xheWzd99ihkDSV43gGzrA',
    appId: '1:112889610100:ios:ff5507b9e9fdd300d63621',
    messagingSenderId: '112889610100',
    projectId: 'sptify00010101',
    storageBucket: 'sptify00010101.appspot.com',
    iosBundleId: 'com.example.spotifyApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCIXWrvhqLKuQ-XOpb7g37vCvxTCj30L6Q',
    appId: '1:112889610100:web:13c0a13d3b72e4ffd63621',
    messagingSenderId: '112889610100',
    projectId: 'sptify00010101',
    authDomain: 'sptify00010101.firebaseapp.com',
    storageBucket: 'sptify00010101.appspot.com',
  );
}
